# Generated by Django 5.2.6 on 2025-09-15 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='difficulty_level',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='importance_level',
        ),
        migrations.AddField(
            model_name='subject',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'ง่าย'), (2, 'ปานกลาง'), (3, 'ยาก')], default=2),
        ),
        migrations.AddField(
            model_name='subject',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='subject_files/'),
        ),
        migrations.AddField(
            model_name='subject',
            name='importance',
            field=models.IntegerField(choices=[(1, 'น้อย'), (2, 'ปานกลาง'), (3, 'มาก')], default=2),
        ),
        migrations.AlterField(
            model_name='file',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_files', to='core.subject'),
        ),
        migrations.AlterField(
            model_name='planactivity',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='exam_date',
            field=models.DateTimeField(),
        ),
    ]
