# Generated by Django 5.2.6 on 2025-09-15 21:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_subject_difficulty_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAvailability',
            fields=[
                ('availability_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('time_slot', models.CharField(choices=[('morning', '06:00-12:00'), ('afternoon', '13:00-18:00'), ('evening', '18:00-22:00'), ('night', '22:00-02:00')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'day_of_week', 'time_slot')},
            },
        ),
    ]
