# Generated by Django 5.2.6 on 2025-09-19 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_useravailability'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('session_duration', models.IntegerField(default=60)),
                ('break_duration', models.IntegerField(default=10)),
                ('notifications_enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
