# Generated by Django 5.2.6 on 2025-12-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_studysession_google_event_id_studysession_is_synced_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='file',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
