# Generated by Django 5.2.6 on 2025-12-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_file_options_file_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_url',
        ),
        migrations.AddField(
            model_name='file',
            name='actual_file',
            field=models.FileField(blank=True, null=True, upload_to='subject_materials/'),
        ),
    ]
