# Generated by Django 5.2.6 on 2025-12-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_file_file_url_file_actual_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={},
        ),
        migrations.RemoveField(
            model_name='file',
            name='actual_file',
        ),
        migrations.RemoveField(
            model_name='file',
            name='order',
        ),
        migrations.AddField(
            model_name='file',
            name='file_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
