# Generated by Django 5.2.6 on 2025-12-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_file_options_remove_file_actual_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='file',
            name='file_url',
        ),
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(default='', upload_to='subject_materials/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
