# Generated by Django 5.2.6 on 2026-01-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_file_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='academic_goal',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='เป้าหมายการเรียน (เช่น GPA 4.00)'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='bio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='คติประจำใจ'),
        ),
    ]
