# Generated by Django 5.2.6 on 2026-01-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_customuser_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useravailability',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='useravailability',
            name='hour',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='useravailability',
            name='time_slot',
        ),
    ]
