# Generated by Django 5.2.6 on 2026-01-19 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_useravailability_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useravailability',
            unique_together={('user', 'day_of_week', 'hour')},
        ),
    ]
