# Generated by Django 5.2.6 on 2026-01-20 15:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('bug', 'แจ้งปัญหาการใช้งาน (Bug)'), ('feature', 'เสนอแนะฟีเจอร์ใหม่ (Feature Request)'), ('content', 'เนื้อหาผิดพลาด (Content Issue)'), ('other', 'อื่นๆ (Other)')], default='other', max_length=20)),
                ('message', models.TextField(verbose_name='รายละเอียด')),
                ('rating', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
